name: .NET Core CI

on: [push, pull_request]

jobs:
  test:
    name: .Net Core ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['2.1', '3.1']
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2.2.0

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1
        
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 2.1
        
    - name: Tests
      run: dotnet test --framework netcoreapp${{ matrix.framework }}
